applications:
  # bun:
  #   source:
  #     root: bun
  #   type: "nodejs:20"
  #   build:
  #     flavor: none
  #   hooks:
  #     build: |
  #       set -e
  #       bun install
  #   web:
  #     commands:
  #       start: "bun index.ts"

  # deno:
  #   source:
  #     root: deno
  #   stack: ['deno']
  #   variables:
  #     env:
  #       DENO_DIR: './cache'
  #   hooks:
  #     build: |
  #       set -e
  #       deno cache deno.json
  #   web:
  #     commands:
  #       start: 'deno run --allow-env --allow-net --allow-read main.ts'

  nodejs:
    source:
      root: nodejs
    type: "nodejs:20"
    build:
      flavor: none
    hooks:
      build: |
        set -e
        npm install
        npm run build
    web:
      commands:
        start: "npm start"


routes:
  # "https://bun.{default}/":
  #   type: upstream
  #   upstream: "bun:http"
  # "https://deno.{default}/":
  #   type: upstream
  #   upstream: "deno:http"
  "https://{default}/":
    type: upstream
    upstream: "nodejs:http"
