applications:

    main_app:
        stack: []
        source:
            root: main
        web:
            locations:
                /:
                    root: "public"
                    index:
                        - index.html

    bun_app: 
        source:
            root: bun
        stack:
            - bun@1
        hooks:
            build: |
                set -e
                bun install
        web:
            commands:
                start: bun start

    nodejs_app: 
        source:
            root: nodejs
        type: "nodejs:20"
        build:
            flavor: none
        hooks:
            build: pnpm install

        # stack:
        #     - nodejs@22
        # hooks:
        #     build: |
        #         set -e
        #         npm install
        #         npm run build

        web:
            commands:
                start: pnpm run start

    deno_app: 
        source:
            root: deno
        stack:
            - deno
        variables:
            env:
                DENO_DIR: "./cache"
        hooks:
            build: |
                set -e
                deno cache deno.json
        web:
            commands:
                start: deno task start

routes:

    "https://{default}/":
        type: upstream
        primary: true
        upstream: "main_app:http"
    "https://www.{default}":
        type: redirect
        to: "https://{default}/"

    "https://{default}/bun":
        type: upstream
        upstream: "bun_app:http"
    "https://www.{default}/bun":
        type: redirect
        to: "https://{default}/bun"

    "https://{default}/nodejs":
        type: upstream
        upstream: "nodejs_app:http"
    "https://www.{default}/nodejs":
        type: redirect
        to: "https://{default}/nodejs"

    "https://{default}/deno":
        type: upstream
        upstream: "deno_app:http"
    "https://www.{default}/deno":
        type: redirect
        to: "https://{default}/deno"
